version: 0.2

phases:
  build:
    commands:
    - echo Entered the buid phase
    - mvn clean package
  post_build:
    commands:
    - echo Build completed successfully
artifacts:
  files:
    - target/CapstoneProjectTushar.jar
  discard-paths: yes